### ISSUE TITLE
Is there any way to change the port?

### ISSUE THREAD

**Issue by RakouskyS** [StarshipEngineer/OpenVPN-Setup#14]

**Comment by Bucky-McDonuts** [comment]
I edited the /etc/openvpn/server.conf file and restarted the service after everything was set up to change the port.  Just make sure you also edit the /etc/openvpn/easy-rsa/keys/Default.txt file as well before you go making profiles.  

It would be neat to add this to the script somehow.

**Comment by RakouskyS** [comment]
Thank you!

**Comment by StarshipEngineer** [comment]
I'll try to add the option to specify port during setup when I test the script on the new standard Raspbian Jessie distro, but it'll be a while before I have time to do that.
