### ISSUE TITLE
Does it start ?

### ISSUE THREAD

**Issue by Kajpio** [StarshipEngineer/OpenVPN-Setup#24]
Sorry it's not an issue, I doing the 1 step the 2 step, transferring my ovpn configuration to my IPad.
And I 'm trying to connect but it's not working (connection timed out). So maybe the server isn't started
so how can i check it, and how I identify the problem?
Thanks for this awesome work and support ! :)

**Comment by dominicjordan** [comment]
Just finished installing and I got the same issue. I think it might be because I didnt run the openvpnsetup.sh script as sudo so I removed everything and it is now reinstalling.

**Comment by Kajpio** [comment]
yeah same here ! I've done it with sudo too...

**Comment by StarshipEngineer** [comment]
I'm currently still having this issue myself. My best guess is that there's some issue with OpenVPN getting through the Pi's firewall, or something to do with dhcp. I'll help working on it as I have time, I'd really like to get this running on Jessie.

**Comment by Kajpio** [comment]
Okay because I installed Wheezy, it's been too long, and I needed it. So on Wheezy it's work perfectly!

**Comment by dominicjordan** [comment]
@Kajpio 
Hmm wait, so you installed Wheezy on your PI and then the script git://github.com/StarshipEngineer/OpenVPN-Setup worked?

@StarshipEngineer When do you expect the Jessie version to be up and running?

**Comment by Kajpio** [comment]
yep I did, hum semi perfectly in fact, I can connect to my VPN in LAN or in cellular but I can't reach the internet. I'm working on it

**Comment by Kajpio** [comment]
MAN IT'S FINALLY WORKING *_*
So my problem was that my raspberry pi is connected by a USB wifi Dongle, so when you run the script is setup to rout all the trafic on eth0, you just need to do a "sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 (not eth0) -j MASQUERADE" and you do a "sudo service openvpn restart" and it's done ! :)
Do you want me to close the issue ?

**Comment by dominicjordan** [comment]
Hmm weird, I have my PI on eth0. No wireless..

**Comment by vinnyfiore** [comment]
Kajpio, what did you actually run? Your command doesn't seem to do anything for me (after removing "(not eth0)" and I'm on wireless...

**Comment by Kajpio** [comment]
@vinnyfiore i've done "sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o wlan0 -j MASQUERADE" it's enable data to be route to the internet from the raspberry pi. I'm not sure to understand your question...

**Comment by george-viaud** [comment]
This solved my problem.  Thanks!
Note:  Updated /etc/firewall-openvpn-rules.sh and OpenVPN-Setup/firewall-openvpn-rules.txt

Perhaps the installer script should be modified to enumerate the network devices available now that R-Pi comes w/ an integrated wlan adapter?  My script-fu w/ regards to bash is not very strong otherwise I'd do it myself.
