### ISSUE TITLE
The script assumes that it is located in /home/pi

### ISSUE THREAD

**Issue by NanoTrasen-Inc** [StarshipEngineer/OpenVPN-Setup#30]
An example would be line 66 of install.sh.

The readme doesn't explicitly state that it has to be executed in /home/pi.
I had cloned it in /home/pi/Desktop which caused the script to skip asking me for location, organization, etc.

**Perhaps replace the text**
`cd`
`git clone git://github.com/StarshipEngineer/OpenVPN-Setup`
**in the README with**
`cd ~`
`git clone git://github.com/StarshipEngineer/OpenVPN-Setup`
**as a fix?**

I'm just a linux noob, so forgive me if I'm incorrect in any way.

**Comment by MartialDiplomacy** [comment]
This actually skips asking me if I want to sign the certificate too, which seems like it would be important.
