### ISSUE TITLE
Port 1194 not open

### ISSUE THREAD

**Issue by Brewmaster9** [StarshipEngineer/OpenVPN-Setup#35]
Thanks very much for the script. 
I've installed the server and I can't connect via any client. I have checked the usual things like port forwarding etc, which all look fine. When I check port status of port 1194 it doesn't appear to be listening. I have done a port scan and ssh and vnc ports are listening fine. I have configured a static ip, which I am port-forwarding to. When I reboot the pi, it reports that that it can't connect to the openvnp server. However when I check post boot, it appears to be running. I can create client files, but when i try to connect (locally and externally) it just hangs (tcp handshake error) and the client log reports no data received from server. I am fairly new to the Raspberry pi, so looking for a few pointers. I've tried re-installing and double checking syntax etc. 

Thank you in anticipation.

**Comment by Brewmaster9** [comment]
Port 1194 issue solved (if it ever was an issue). This works on my Raspberry Pi 2.

Having tried to configure the server on a NOOBS 1.7/8 Raspbian installation, I decided to go back to basics and install the latest RasbianJessie iso. The steps that worked for me...

Static IP Set on Pi
Static IP reserved on router
Port forward 1194 to Raspberry Pi IP on router.

1. In raspi-config 
Expand file system
Auto-login boot to command line (don't think GUI helps)
Change Password
Wait for Network at Boot (Enable long wait) This makes sure your local pi IP connects to the server on re-boot.
Enable ssh

When all the above is set up, script runs like a dream, using steps in tutorial. Openvpn client files downloaded using SFTP in Cyberduck to Mac. 

Openvpn clients on iPhone (including cellphone 3g/4g access, iPad & Mac all tested and work 100%. The upload/download speed is good on Rpi2.

Thanks again for the script.

**Comment by StarshipEngineer** [comment]
Thanks for reporting back with a fix. I was at a loss to explain the problem, but it multiple users were experiencing it. I'll add a note to the documentation to include the extra setup step you used.
